name: kpi_reliability_dbt
version: "1.0.0"
config-version: 2

profile: kpi_reliability_dbt

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  kpi_reliability_dbt:
    staging:
      +materialized: view
      +schema: dbt_staging
    intermediate:
      +materialized: view
      +schema: dbt_intermediate
    marts:
      +materialized: table
      +schema: dbt_marts
      +persist_docs:
        relation: true
        columns: true

